### ISSUE TITLE
Missing `test_dataset_with_similarity_idx.csv` in provided datasets

### ISSUE THREAD

**Issue by shania830** [wangxr0526/EasIFA#1]
Hello,

I’ve encountered an issue when trying to reproduce the results using the code in the `scoring_results.ipynb` file. In the first cell, a dataset path is specified for test_dataset_with_similarity_idx.csv:
`test_dataset_with_similarity_idx_path = '../dataset/ec_site_dataset/uniprot_ecreact_cluster_split_merge_dataset_limit_100/test_dataset_with_similarity_idx.csv'`

However, this CSV file is not included in the repository, nor is it in the zip files provided in the dataset download links (`dataset.zip`). As a result, the code cannot be executed as intended.

Could you kindly provide this missing file or clarify where we can find it?

Thank you!

**Comment by wangxr0526** [comment]
We have upload the missing files in the repository. Thank you for your support of our work.
