### ISSUE TITLE
Problems with active site labeling during training

### ISSUE THREAD

**Issue by MichaelAbel1** [wangxr0526/EasIFA#10]
Why is it that when active sites are predicted, in the calculate_active_sites method of class EnzymeDataset, all sites where site_label is present are labeled as 1, instead of active sites being labeled as 1

**Comment by wangxr0526** [comment]
When predicting active sites in a binary classification task for enzymes, we consider Binding Site, Catalytic Site (referred to as Active Site in UniProt, as noted in the paper, annotation "d" in Table 1), and Other Site as active sites. The `EnzymeDataset` class serves as a basic class, with its `calculate_active_sites` method used to convert the labels of all the aforementioned sites. If you want to convert these sites separately, you need to use the `EnzymeReactionSiteTypeDataset` class, which provides the `calculate_active_site_types` method to achieve this purpose.
