### ISSUE TITLE
Conda Environment

### ISSUE THREAD

**Issue by pgmikhael** [wangxr0526/EasIFA#2]
Hi!

Thank you all for putting the code together for this project – the work is really exciting! 

I'm getting all sorts of errors when attempting to setup the environment from the yml file. There appears to be many packages with versions that are not compatible. There are also other smaller issues (for instance the name of the environment is different from what is expected in the README, there isn't an esm version 2.0.1, etc.). I spent half of a day trying to reconcile the packages and reconstruct the environment. It would be super helpful if you could double check the environment and provide any potential updates that are guaranteed to work.

Thank you!

**Comment by wangxr0526** [comment]
Thank you very much for your attention and recognition of EasIFA!  :satisfied:  We have written an automated configuration script, in which we use the packaged Python environment we shared to reduce compatibility issues. The current configuration steps are as follows: 
```
git clone https://github.com/wangxr0526/EasIFA.git
cd EasIFA
chmod +x ./setup_EasIFA.sh
./setup_EasIFA.sh
conda activate easifa_env
```

Additionally, if users want to quickly deploy the EasIFA model, they can try it out in Gitpod. We have previously set up an automated deployment process there. Thank you for your suggestions!

**Comment by pgmikhael** [comment]
This seems to work. Thank you!
