### ISSUE TITLE
when I python download_data.py,download Failure

### ISSUE THREAD

**Issue by chen-15969746967** [wangxr0526/EasIFA#4]
I found this error while downloading data, but I couldn't find the file EaseIFA/dataset/ec_Site_dataset/structures/urls.txt
---------------------------------------------------------------------
(easifa_env) [@bdc3 EasIFA]$ python download_data.py
Downloading files...
/project/EasIFA/checkpoints exists, skip downloading
/project/EasIFA/dataset exists, skip downloading
Download structure files for /project/EasIFA/dataset/ec_site_dataset/uniprot_ecreact_cluster_split_merge_dataset_limit_100
aria2c -i /project/EasIFA/dataset/ec_site_dataset/structures/urls.txt -x 16 -d /project/EasIFA/dataset/ec_site_dataset/structures/alphafolddb_download Failure!
Download structure files for /project/EasIFA/dataset/mcsa_fine_tune/normal_mcsa
aria2c -i /project/EasIFA/dataset/mcsa_fine_tune/structures/urls.txt -x 16 -d /project/EasIFA/dataset/mcsa_fine_tune/structures/alphafolddb_download Failure!

thank you

**Comment by wangxr0526** [comment]
Thank you for your question. We have optimized the `download_data.py` script. Please update the code and try again.
