### ISSUE TITLE
Can I ask you how you got those raw data for building the dataset, for example rxnaamapper_external_test_set.csv, I can't find the code to generate these files

### ISSUE THREAD

**Issue by MichaelAbel1** [wangxr0526/EasIFA#6]

**Comment by wangxr0526** [comment]
You can find this file in the attachment [rxnaamapper_external_test_set.csv](https://github.com/user-attachments/files/17189644/rxnaamapper_external_test_set.csv), but it is not important. It was an early attempt in this project.
