### ISSUE TITLE
conda error

### ISSUE THREAD

**Issue by chen-15969746967** [wangxr0526/EasIFA#7]
Hello

Thank you all for putting the code together for this project – the work is really exciting!

I encountered conflicts between PyTorch, NumPy, DGL, RxnFP, and others while installing.

Thank you!

**Comment by wangxr0526** [comment]
Thank you very much for your recognition of our work. We have provided an automated configuration [script ](https://github.com/wangxr0526/EasIFA/blob/master/setup_EasIFA.sh)and directly made the Python environment accessible. You can use the script for configuration or manually set up the relevant [Python environment](https://drive.google.com/uc?id=1kLIx2h6kPk6OvRVPWWqJvoKAYVvBx80x) as needed.
