### ISSUE TITLE
Training the models

### ISSUE THREAD

**Issue by aparsanMIT** [wangxr0526/EasIFA#9]
Hi!

I am attempting to train the models on the data from scratch, and then testing and reproducing results. Is there a specific script/procedure I should run for training?

**Comment by wangxr0526** [comment]
You can roughly follow the code here [`dataset_preprocess`](dataset_preprocess) to prepare your data. It doesn’t need to be exactly the same, just make sure that the final file format is consistent with what I used for training (also, be mindful of the similarity threshold for enzyme sequences between the training, validation, and test sets). All the data preparation scripts are here, and you can modify them according to your needs.
